-- Seed sticker_groups: FWC + 48 teams + Coca-Cola

INSERT INTO sticker_groups (name, code, type, description, sticker_count) VALUES
('FIFA World Cup', 'FWC', 'fwc', 'Figurinhas especiais de abertura', 11),
('Coca-Cola', 'CC', 'sponsor', 'Figurinhas especiais Coca-Cola', 14),
('México', 'MEX', 'team', 'Seleção do México', 20),
('África do Sul', 'RSA', 'team', 'Seleção da África do Sul', 20),
('Coreia do Sul', 'KOR', 'team', 'Seleção da Coreia do Sul', 20),
('Tchéquia', 'CZE', 'team', 'Seleção da Tchéquia', 20),
('Canadá', 'CAN', 'team', 'Seleção do Canadá', 20),
('Bósnia e Herzegovina', 'BIH', 'team', 'Seleção da Bósnia e Herzegovina', 20),
('Catar', 'QAT', 'team', 'Seleção do Catar', 20),
('Suíça', 'SUI', 'team', 'Seleção da Suíça', 20),
('Brasil', 'BRA', 'team', 'Seleção do Brasil', 20),
('Marrocos', 'MAR', 'team', 'Seleção de Marrocos', 20),
('Haiti', 'HAI', 'team', 'Seleção do Haiti', 20),
('Escócia', 'SCO', 'team', 'Seleção da Escócia', 20),
('Estados Unidos', 'USA', 'team', 'Seleção dos Estados Unidos', 20),
('Paraguai', 'PAR', 'team', 'Seleção do Paraguai', 20),
('Austrália', 'AUS', 'team', 'Seleção da Austrália', 20),
('Turquia', 'TUR', 'team', 'Seleção da Turquia', 20),
('Alemanha', 'GER', 'team', 'Seleção da Alemanha', 20),
('Curaçao', 'CUW', 'team', 'Seleção de Curaçao', 20),
('Costa do Marfim', 'CIV', 'team', 'Seleção da Costa do Marfim', 20),
('Equador', 'ECU', 'team', 'Seleção do Equador', 20),
('Países Baixos', 'NED', 'team', 'Seleção dos Países Baixos', 20),
('Japão', 'JPN', 'team', 'Seleção do Japão', 20),
('Suécia', 'SWE', 'team', 'Seleção da Suécia', 20),
('Tunísia', 'TUN', 'team', 'Seleção da Tunísia', 20),
('Bélgica', 'BEL', 'team', 'Seleção da Bélgica', 20),
('Egito', 'EGY', 'team', 'Seleção do Egito', 20),
('Irã', 'IRN', 'team', 'Seleção do Irã', 20),
('Nova Zelândia', 'NZL', 'team', 'Seleção da Nova Zelândia', 20),
('Espanha', 'ESP', 'team', 'Seleção da Espanha', 20),
('Cabo Verde', 'CPV', 'team', 'Seleção de Cabo Verde', 20),
('Arábia Saudita', 'KSA', 'team', 'Seleção da Arábia Saudita', 20),
('Uruguai', 'URU', 'team', 'Seleção do Uruguai', 20),
('França', 'FRA', 'team', 'Seleção da França', 20),
('Senegal', 'SEN', 'team', 'Seleção do Senegal', 20),
('Iraque', 'IRQ', 'team', 'Seleção do Iraque', 20),
('Noruega', 'NOR', 'team', 'Seleção da Noruega', 20),
('Argentina', 'ARG', 'team', 'Seleção da Argentina', 20),
('Argélia', 'ALG', 'team', 'Seleção da Argélia', 20),
('Áustria', 'AUT', 'team', 'Seleção da Áustria', 20),
('Jordânia', 'JOR', 'team', 'Seleção da Jordânia', 20),
('Portugal', 'POR', 'team', 'Seleção de Portugal', 20),
('República Democrática do Congo', 'COD', 'team', 'Seleção da RD Congo', 20),
('Uzbequistão', 'UZB', 'team', 'Seleção do Uzbequistão', 20),
('Colômbia', 'COL', 'team', 'Seleção da Colômbia', 20),
('Inglaterra', 'ENG', 'team', 'Seleção da Inglaterra', 20),
('Croácia', 'CRO', 'team', 'Seleção da Croácia', 20),
('Gana', 'GHA', 'team', 'Seleção de Gana', 20),
('Panamá', 'PAN', 'team', 'Seleção do Panamá', 20);
